# -*- coding: utf-8 -*-
"""codigo_multiplicar_matrices.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ji8V1Wwd0QAT_1346fdtDUUKbzYg_PE4
"""

import sympy as sp

# 1. Definir la variable simbólica theta
theta = sp.symbols('theta')

# 2. Definir la matriz de rotación en Z (A1)
Rz = sp.Matrix([
    [sp.cos(theta), -sp.sin(theta), 0],
    [sp.sin(theta), sp.cos(theta), 0],
    [0, 0, 1]
])

# 3. Definir la matriz de rotación
R_r = sp.Matrix([
    [0, 0, 1],
    [0, 1, 0],
    [-1, 0, 0]
])

# 4. Realizar la multiplicación de matrices
resultado = Rz * R_r

# 5. Mostrar el resultado de forma elegante
print("Resultado de Rz(theta) * Ry(90):")
sp.pprint(resultado)